server.port=8081

# 🗄️ DATABASE (Supabase / PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bidbrowflwommbmfksno
spring.datasource.password=FrostyTiger2026Moon54

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ☁️ SUPABASE STORAGE CONFIG
supabase.url=https://bidbrowflwommbmfksno.supabase.co
supabase.bucket=uploads
supabase.apiKey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZGJyb3dmbHdvbW1ibWZrc25vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODk2NDA2NSwiZXhwIjoyMTA0NTQwMDY1fQ.Sk7UwXMBjt-tKt0BKHqtS4kf_JsLQw7OXJdC68pyJVQ

# 🔐 JWT Secret (ใช้ภายหลังตอน Auth)
jwt.secret=jXWlpsge7MhkaoxQZ2EbsdGY2uynUNiceJ8vy/qG8x71rRSIOGo82cffQt/kdLUmcwH7LzsP31LhBMNu+iRwCQ==
jwt.expiration=86400000
